version: '3'

services: 
    db-numbi:
        image: postgres
        container_name: nubi_db
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: nubi_survery
        volumes: 
            - database:/var/lib/postgresql/data
        ports: 
            - 5432:5432
volumes: 
    database: