version: '3'

services: 
    database:
        image: postgres
        container_name: nubi_db
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: nubi_survery
        volumes: 
            - ./database:/var/lib/postgresql/data